name: ct2hair
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.10.6
  - matplotlib==3.6.2
  - numpy==1.23.5
  - scipy==1.11.1
  - tensorboardX==2.6.1
  - tqdm==4.64.1
  - trimesh==3.17.1
  - termcolor==2.3.0
  - pyhocon
  - ninja
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu115
    - torch==1.11.0+cu115
    - open3d==0.16.0
    - opencv_python==4.6.0.66
    - scikit_learn==1.3.0
    - splines==0.2.0
    - libigl==2.4.1
